development: &development
  adapter: postgresql
  host: localhost
  database: photo_s3_uploader_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: photo_s3_uploader_test
  encoding: unicode
